#ifndef COMMONDEF_H
#define COMMONDEF_H

// App
#define APP_WIDTH   1920
#define APP_HEIGHT  1080

// Masthead
#define MASTHEAD_WIDTH    1920
#define MASTHEAD_HEIGHT   56
#define MASTHEAD_PADDING_LEFT 16
#define MASTHEAD_PADDING_RIGHT 16
#define BTN_GUIDE_SIZE         40

// ICON
#define ICON_SIZE 24

// Masthead Start
#define MASTHEAD_START_POS_X 16
#define MASTHEAD_START_POS_Y 0
#define MASTHEAD_START_WIDTH 169
#define MASTHEAD_START_HEIGHT 56

// Masthead Center
#define MASTHEAD_CENTER_POS_X   400
#define MASTHEAD_CENTER_POS_Y   6
#define MASTHEAD_CENTER_WIDTH   1000
#define MASTHEAD_CENTER_HEIGHT  50
#define SUBFUNCTION_BTN_SIZE    48
#define SUBFUNCITON_FONT_FAMILY "Arial"
#define SUBFUNCTION_FONT_SIZE   5
#define SUBFUNCTION_FONT_BOLD   1
#define SUBFUNCTION_BTN_SPACING 9


// Masthead End

#endif // COMMONDEF_H
